// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNoGRTUcm74DGaIfknwbt7omzwp4vWiJI',
    appId: '1:399366990643:web:af9f0e2bd714845717ac46',
    messagingSenderId: '399366990643',
    projectId: 'flavorprod-4c421',
    authDomain: 'flavorprod-4c421.firebaseapp.com',
    storageBucket: 'flavorprod-4c421.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6_D51Ee6jt2Pkfuk-Elx0tu6il8bi5D4',
    appId: '1:399366990643:android:b63526cd3c65707917ac46',
    messagingSenderId: '399366990643',
    projectId: 'flavorprod-4c421',
    storageBucket: 'flavorprod-4c421.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYLFqzm1PE6qJFF0KCHqRWGLrNfMpu9kw',
    appId: '1:399366990643:ios:111aabbdc6f2d94417ac46',
    messagingSenderId: '399366990643',
    projectId: 'flavorprod-4c421',
    storageBucket: 'flavorprod-4c421.appspot.com',
    iosClientId:
        '399366990643-ugr8uob4282spq3supq2v3tc0hk3g1vm.apps.googleusercontent.com',
    iosBundleId: 'com.seniorturkmen.flavorDemo',
  );
}
