// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxvL3fqoT40WLE3CklK75balIXxq-V-sQ',
    appId: '1:480093841198:web:e9b76352c43f76faf1fcbf',
    messagingSenderId: '480093841198',
    projectId: 'flavordev-cdc4a',
    authDomain: 'flavordev-cdc4a.firebaseapp.com',
    storageBucket: 'flavordev-cdc4a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRF430fd9wYH3gDFLgNhwkPkdZE77UshI',
    appId: '1:480093841198:android:ec0d1f13b72d59ebf1fcbf',
    messagingSenderId: '480093841198',
    projectId: 'flavordev-cdc4a',
    storageBucket: 'flavordev-cdc4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0LkTvlXGo_fqg6ufqOpDZ3rqabSpefzQ',
    appId: '1:480093841198:ios:84f615cbd072d606f1fcbf',
    messagingSenderId: '480093841198',
    projectId: 'flavordev-cdc4a',
    storageBucket: 'flavordev-cdc4a.appspot.com',
    iosClientId:
        '480093841198-68c62goahid3g7qfrmj8u700r5tmmpq4.apps.googleusercontent.com',
    iosBundleId: 'com.seniorturkmen.flavorDemoDev',
  );
}
